"""Verification report generation for download."""

from __future__ import annotations

import csv
import io
import json
from html import escape

from src.fact_checker import FactCheckReport


def generate_markdown_report(report: FactCheckReport) -> str:
    """Build a Markdown verification report."""
    lines = [
        "# Fact-Check Verification Report",
        "",
        f"**Document:** {report.filename}  ",
        f"**Pages analyzed:** {report.page_count}  ",
        f"**Generated:** {report.generated_at}  ",
        "",
        "## Summary",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Trust Score | **{report.trust_score}/100** |",
        f"| Source Credibility | **{report.source_credibility_score}/100** |",
        f"| Claims analyzed | {len(report.claims)} |",
        f"| Verified | {report.verified_count} |",
        f"| Inaccurate | {report.inaccurate_count} |",
        f"| False | {report.false_count} |",
        "",
        "---",
        "",
    ]

    for idx, claim in enumerate(report.claims, start=1):
        lines.extend(
            [
                f"## Claim {idx}",
                "",
                f"**Claim:** {claim.claim}  ",
                f"**Type:** {claim.claim_type}  ",
                f"**Status:** {claim.status}  ",
                f"**Confidence:** {claim.confidence_score}%  ",
                f"**Source Credibility:** {claim.source_credibility_score}/100  ",
                "",
                f"**Correct Fact:** {claim.correct_fact}",
                "",
                "**Reasoning:**",
                claim.reasoning,
                "",
                "**Sources:**",
            ]
        )
        if claim.source_urls:
            for url in claim.source_urls:
                lines.append(f"- {url}")
        else:
            lines.append("- No sources cited")

        if claim.source_details:
            lines.append("")
            lines.append("**Source Breakdown:**")
            for detail in claim.source_details:
                lines.append(
                    f"- {detail['domain']} ({detail['category']}): "
                    f"{detail['credibility_score']}/100"
                )

        lines.extend(["", "---", ""])

    lines.append("*Report generated by FactChecker AI*")
    return "\n".join(lines)


def generate_html_report(report: FactCheckReport) -> str:
    """Build an HTML verification report suitable for download."""
    claim_blocks: list[str] = []
    status_colors = {
        "Verified": "#059669",
        "Inaccurate": "#d97706",
        "False": "#dc2626",
    }

    for idx, claim in enumerate(report.claims, start=1):
        color = status_colors.get(claim.status, "#64748b")
        sources_html = ""
        if claim.source_urls:
            links = "".join(
                f'<li><a href="{escape(url)}" target="_blank">{escape(url)}</a></li>'
                for url in claim.source_urls
            )
            sources_html = f"<ul>{links}</ul>"
        else:
            sources_html = "<p><em>No sources cited</em></p>"

        claim_blocks.append(
            f"""
            <section class="claim-card">
              <h3>Claim {idx}</h3>
              <p class="claim-text">{escape(claim.claim)}</p>
              <div class="meta">
                <span class="badge" style="background:{color}">{escape(claim.status)}</span>
                <span>Type: {escape(claim.claim_type)}</span>
                <span>Confidence: {claim.confidence_score}%</span>
                <span>Source Credibility: {claim.source_credibility_score}/100</span>
              </div>
              <div class="fact-box">
                <strong>Correct Fact</strong>
                <p>{escape(claim.correct_fact)}</p>
              </div>
              <p><strong>Reasoning:</strong> {escape(claim.reasoning)}</p>
              <strong>Sources</strong>
              {sources_html}
            </section>
            """
        )

    claims_html = "\n".join(claim_blocks)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Fact-Check Report — {escape(report.filename)}</title>
  <style>
    body {{
      font-family: 'Segoe UI', system-ui, sans-serif;
      background: #f8fafc;
      color: #0f172a;
      margin: 0;
      padding: 2rem;
      line-height: 1.6;
    }}
    .container {{ max-width: 900px; margin: 0 auto; }}
    h1 {{ color: #1e293b; margin-bottom: 0.25rem; }}
    .subtitle {{ color: #64748b; margin-bottom: 2rem; }}
    .summary {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
      gap: 1rem;
      margin-bottom: 2rem;
    }}
    .metric {{
      background: white;
      border-radius: 12px;
      padding: 1.25rem;
      box-shadow: 0 1px 3px rgba(0,0,0,0.08);
      text-align: center;
    }}
    .metric .value {{ font-size: 2rem; font-weight: 700; color: #2563eb; }}
    .metric .label {{ font-size: 0.85rem; color: #64748b; }}
    .claim-card {{
      background: white;
      border-radius: 12px;
      padding: 1.5rem;
      margin-bottom: 1.25rem;
      box-shadow: 0 1px 3px rgba(0,0,0,0.08);
    }}
    .claim-text {{ font-size: 1.05rem; font-weight: 500; }}
    .meta {{ display: flex; flex-wrap: wrap; gap: 0.75rem; margin: 1rem 0; font-size: 0.9rem; }}
    .badge {{
      color: white;
      padding: 0.2rem 0.65rem;
      border-radius: 999px;
      font-weight: 600;
      font-size: 0.8rem;
    }}
    .fact-box {{
      background: #f1f5f9;
      border-left: 4px solid #2563eb;
      padding: 1rem;
      border-radius: 0 8px 8px 0;
      margin: 1rem 0;
    }}
    a {{ color: #2563eb; }}
  </style>
</head>
<body>
  <div class="container">
    <h1>Fact-Check Verification Report</h1>
    <p class="subtitle">{escape(report.filename)} · {report.page_count} pages · {escape(report.generated_at)}</p>

    <div class="summary">
      <div class="metric">
        <div class="value">{report.trust_score}</div>
        <div class="label">Trust Score</div>
      </div>
      <div class="metric">
        <div class="value">{report.source_credibility_score}</div>
        <div class="label">Source Credibility</div>
      </div>
      <div class="metric">
        <div class="value">{report.verified_count}</div>
        <div class="label">Verified</div>
      </div>
      <div class="metric">
        <div class="value">{report.inaccurate_count}</div>
        <div class="label">Inaccurate</div>
      </div>
      <div class="metric">
        <div class="value">{report.false_count}</div>
        <div class="label">False</div>
      </div>
    </div>

    {claims_html}

    <p style="color:#94a3b8;font-size:0.85rem;margin-top:2rem;">
      Report generated by FactChecker AI
    </p>
  </div>
</body>
</html>"""


def generate_json_report(report: FactCheckReport) -> str:
    """Serialize report to JSON."""
    payload = {
        "filename": report.filename,
        "page_count": report.page_count,
        "generated_at": report.generated_at,
        "trust_score": report.trust_score,
        "source_credibility_score": report.source_credibility_score,
        "summary": {
            "total_claims": len(report.claims),
            "verified": report.verified_count,
            "inaccurate": report.inaccurate_count,
            "false": report.false_count,
        },
        "claims": [
            {
                "claim": c.claim,
                "claim_type": c.claim_type,
                "status": c.status,
                "confidence_score": c.confidence_score,
                "correct_fact": c.correct_fact,
                "source_urls": c.source_urls,
                "reasoning": c.reasoning,
                "source_credibility_score": c.source_credibility_score,
                "source_details": c.source_details,
            }
            for c in report.claims
        ],
    }
    return json.dumps(payload, indent=2)


def generate_csv_report(report: FactCheckReport) -> str:
    """Serialize claims to CSV."""
    buffer = io.StringIO()
    writer = csv.writer(buffer)
    writer.writerow(
        [
            "Claim",
            "Type",
            "Status",
            "Confidence Score",
            "Correct Fact",
            "Source URLs",
            "Source Credibility Score",
            "Reasoning",
        ]
    )
    for claim in report.claims:
        writer.writerow(
            [
                claim.claim,
                claim.claim_type,
                claim.status,
                claim.confidence_score,
                claim.correct_fact,
                " | ".join(claim.source_urls),
                claim.source_credibility_score,
                claim.reasoning,
            ]
        )
    return buffer.getvalue()
